FoundationEnglish = float(input("Please input Foundation English score: "))
GeneralBusiness = float(input("Please input General Business score: "))
IntroductionToComputerSystems = float(input("Please input Introduction to Computer Systems score: "))
ComputerProgramming = float(input("Please input Introduction to Computer Programming score: "))

print("--- Your Score ---")
print("Foundation English : ", FoundationEnglish)
print("General Business : ", GeneralBusiness)
print("Introduction to Computer Systems : ", IntroductionToComputerSystems)
print("Computer Programming : ", ComputerProgramming)